version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - "4566-4583:4566-4583"
